actors:
  chezou:
    image_url: /images/chezou.jpg
    name: chezou
    url: https://twitter.com/chezou
  suginoy:
    image_url: /images/suginoy.jpg
    name: suginoy
    url: https://twitter.com/suginoy
  mametter:
    image_url: /images/mametter.png
    name: mametter
    url: https://twitter.com/mametter
  moriyoshit:
    image_url: /images/moriyoshit.jpg
    name: moriyoshit
    url: https://twitter.com/moriyoshit
  bonotake:
    image_url: /images/bonotake.jpg
    name: bonotake
    url: https://twitter.com/bonotake
  golden_lucky:
    image_url: /images/golden_lucky.jpg
    name: golden_lucky
    url: https://twitter.com/golden_lucky
  kuenishi:
    image_url: /images/kuenishi.jpg
    name: kuenishi
    url: https://twitter.com/kuenishi
  hurutoriya:
    image_url: /images/hurutoriya.jpg
    name: hurutoriya
    url: https://twitter.com/hurutoriya
  overs_5121:
    image_url: /images/overs_5121.jpg
    name: overs_5121
    url: https://twitter.com/overs_5121
  shiumachi:
    image_url: /images/shiumachi.png
    name: shiumachi
    url: https://twitter.com/shiumachi
author: Aki Ariga
description: Random Facts club is a podcast for things useless for your work
description_long: A podcast for technical random facts, i.e. things useless for your work
email: chezou@randomfacts.club
exclude:
  - docker
  - docker-compose.yml
  - Gemfile
  - Gemfile.lock
  - LICENSE.txt
  - README.md
  - vendor
google_analytics:
hashtag: rfclub
itunes_podcast_url: https://podcasts.apple.com/jp/podcast/random-facts-club/id1462384987
keywords: tech,podcast
language: ja
markdown: kramdown
permalink: /:title
sass:
  sass_dir: css
timezone: Asia/Tokyo
title: Random Facts Club
url: https://randomfacsts.club
