actors:
  chezou:
    image_url: https://pbs.twimg.com/profile_images/3512660657/c7724f0f2022e87c568dec7af95909a6_400x400.jpeg
    name: chezou
    url: http://twitter.com/chezou
  suginoy:
    image_url: https://pbs.twimg.com/profile_images/641060075298095104/qANwP39K_400x400.jpg
    name: suginoy
    url: http://twitter.com/suginoy
author: chezou
description: Random Facts club is a podcast for things useless for your work
description_long: Random Facts club is a podcast for technical random facts, i.e. things useless for your work.
email: chezou@randomfacts.club
exclude:
  - docker
  - docker-compose.yml
  - Gemfile
  - Gemfile.lock
  - LICENSE.txt
  - README.md
  - vendor
google_analytics:
hashtag: rfclub
itunes_podcast_url:
keywords: tech,podcast
language: ja
markdown: kramdown
permalink: /:title
sass:
  sass_dir: css
timezone: Asia/Tokyo
title: Random Facts Club
url: https://randomfacsts.club
